---
title: "Fatala"
output: 
  html_document: 
    theme: cosmo
---
```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(ggridges)
library(gridExtra)
mytheme.dark <-function(legend){
  list= list(theme_light(), scale_color_brewer(legend,palette="Dark2"), 
             scale_fill_brewer(legend,palette="Dark2"), 
             theme(strip.background=element_rect(fill="gray50",colour ="gray50"),
                   plot.title = element_text(hjust = 0.5)))}
```

#Data for selection


```{r}
ListVEM_boot_200=readRDS("/Users/raphaellemomal/these/R/codes/missingActor/SimResults/Fatala_VEM_200.rds")
vec_sdMH_J=do.call(rbind, lapply(ListVEM_boot_200, function(vem){
  if(length(vem)==14){
    J=tail(vem$lowbound$J, 1)
    sdM=apply(vem$M,2, function(x) sd(x))
    sdMH=tail(sdM,2)
    q=ncol(vem$M) ; r=2 ; H=(q-r+1):q
    entrUH=-0.5*sum(log(vem$S[,H]))
    Sbar1=mean(vem$S[,H[1]])
    Sbar2=mean(vem$S[,H[2]])
    res=c(sdMH,J,entrUH,Sbar1,Sbar2)
  }else{
   J=NaN ;sdMH = c(NaN,NaN); entrUH=NaN; Sbar1=NaN; Sbar2=NaN
     res=c(sdMH,J,entrUH,Sbar1,Sbar2)}
}))

dataFatala=data.frame(vec_sdMH_J)
colnames(dataFatala) = c("sd1","sd2","J","penUH","S1","S2")
dataFatala=dataFatala %>% as_tibble() %>% 
  mutate(num=1:nrow(dataFatala), TwoActors=ifelse(log(sd1)>-15 & log(sd2) >-15,"on", "off"))

dataFatala %>% ggplot(aes(J,J-penUH, color=TwoActors))+geom_point()+mytheme.dark("")
dataFatala %>% ggplot(aes(TwoActors,penUH))+geom_boxplot()+mytheme.dark("")

dataFatala %>% ggplot(aes(TwoActors,J+penUH))+geom_boxplot()+mytheme.dark("") # le meilleur modèle pénalisé est dans les off donc ça marche pas
dataFatala %>% ggplot(aes(sd1, sd2, color=penUH))+geom_point()+theme_light()
dataFatala %>% ggplot(aes(log(sd1), log(S1)))+geom_point()+theme_light()
dataFatala %>% ggplot(aes(sd2, S2))+geom_point()+theme_light()
dataFatala %>% ggplot(aes(log(S1),log(S2)))+geom_point()+theme_light()

dataFatala %>% filter(log(S1)<(-0.1),log(S2)<(-0.1))
```

# Visualisation and selection

```{r}
dataFatala=dataFatala %>% filter(!is.na(J))
dataFatala %>% gather(key, value,-J,-num,-TwoActors) %>% 
  ggplot(aes(log(value), color=key, fill=key))+
  geom_histogram(alpha=0.5,bins = 30)+mytheme.dark("")+facet_wrap(~key)

dataFatala %>% gather(key, value, -J,-TwoActors,-num) %>% 
  ggplot(aes(as.factor(J), log(as.numeric(value)), color=key, group=interaction(J,key)))+
  geom_point(position = position_dodge(width=0.5))+mytheme.dark("Sd of Mh:") +labs(x="J",y="value")+
  theme(axis.text.x = element_blank())
 
dataFatala %>%  ggplot(aes(log(sd1), log(sd2), color=J))+
  geom_point()+theme_light()  

dataFatala %>%filter(log(sd1)>-20,log(sd2)>-20) %>%  ggplot(aes(log(sd1), log(sd2), color=J))+
  geom_point()+theme_light()+labs(title="Zoom")


dataFatala  %>% filter(!is.na(J)) %>% 
  ggplot(aes(TwoActors, J))+geom_point()+mytheme.dark("")

dataFatala %>% filter(TwoActors=="on") %>% filter(J==max(J))

VEM_fatala_200=ListVEM_boot_200[[32]]
```

#Result

```{r}
library(ade4)
data(baran95)
counts=as.matrix(baran95$fau)
p=ncol(counts);r=2
H=(p+1):(p+r)
MH=VEM_fatala_200$M[,H]
data=MH %>% as_tibble() %>% mutate(Site=baran95$plan$site, date=baran95$plan$date,
                              Season=unlist(purrr::map(date, function(x){
                                if(x%in%c("oct93","jun93","aug93")) res="Rainy"
                                if(x%in%c("feb94","dec93","apr93")) res="Dry"
                                return(res)
                              }))) %>% 
  mutate(covar=paste(Site, date), covarnum=as.numeric(as.factor(covar))) 

g1<-data %>% 
  ggplot(aes(V1, V2, color=Site, shape=Site))+geom_point()+ 
  labs(x="Mh1",y="Mh2", title="")+scale_shape_discrete("Site",solid = TRUE)+
  scale_color_brewer("Site",palette="Dark2")+theme_light()

g2<-data%>% 
  ggplot(aes(V1, V2, color=Season, shape=Season))+geom_point()+theme_light()+
  scale_color_brewer("Season",palette="Dark2")+scale_shape_discrete("Season")+
  labs(x="Mh1",y=" Mh2", title="")
 g3<-data %>%
  ggplot(aes( V1, Site, color=Site, fill=Site))+
  geom_density_ridges( alpha=0.5)+mytheme.dark("")+
  labs(x="Mh1" ,y="", title="")+guides(color=FALSE, fill=FALSE)
g4<-data %>%
  ggplot(aes( V2, Season, color=Season, fill=Season))+
  geom_density_ridges( alpha=0.5)+mytheme.dark("")+
  labs(x="Mh2",y="", title="")+guides(color=FALSE, fill=FALSE)
grid.arrange(g1, g3,g2, g4, ncol=2)


```

