---
title: "VEMtree: Results"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Simulating data

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(EMtree)
library(PLNmodels)
library(LITree)
library(ggraph)
library(tidygraph)
library(tidyverse)
library(mvtnorm)
library(useful)
library(rlang)
library(mclust)
library(ROCR)
library(MASS)
library(reshape2)#for ggimage
library(gridExtra)

mytheme.light <- list(theme_light(), scale_color_brewer("",palette="Set3"),guides(color=FALSE),
                     theme(strip.background=element_rect(fill="gray50",colour ="gray50"),
                           plot.title = element_text(hjust = 0.5)))

mytheme.dark <- list(theme_light(), scale_color_brewer("",palette="Dark2"),guides(color=FALSE),
                     theme(strip.background=element_rect(fill="gray50",colour ="gray50"),
                           plot.title = element_text(hjust = 0.5)))
# mypal<-c(brewer.pal(3, "Blues"),brewer.pal(3, "Reds"),brewer.pal(3, "Greens"))
# mypal<-c(brewer.pal(8, "Dark2"),"blue","red")
mytheme <- list(theme_light(), scale_fill_brewer("",palette="Dark2"),#scale_colour_hp_d(option = "RavenClaw", name = ""), #scale_color_manual("",values=mypal),
                guides(color=FALSE),
                theme(strip.background=element_rect(fill="gray50",colour ="gray50"),
                      plot.title = element_text(hjust = 0.5)))

source("/Users/raphaellemomal/these/R/codes/missingActor/fonctions-missing.R")

```



```{r}
# simu parameters
set.seed(7)
n=200
p=14
r=1
type="scale-free"
plot=TRUE
 
################
#----- DATA
# simulate graph and omega, then sigma0 and finally counts
data=data_from_scratch(type = type,p = p+r,n = n,signed = FALSE,prob = 5/p,v = 0)
omega=data$omega
hidden=which(diag(omega)%in%sort(diag(omega), decreasing = TRUE)[1:r])[1:r] # on cache les r plus gros
trueClique=which(omega[hidden,-hidden]!=0)
if(plot){
  G=draw_network(1*(omega==1),groupes=1*(diag(omega)==diag(omega)[hidden][1]), 
                 layout="nicely",curv=0,nb=2,pal="black",nodes_label = 1:(p+r))$G
  print(G)
}
Kh  <- omega[hidden,hidden]
Ko  <- omega[-hidden,-hidden]
Koh <- omega[-hidden,hidden]
Km  <- Ko - Koh %*%solve(Kh)%*% t(Koh)
sigmaO=solve(Km)
counts=generator_PLN(sigmaO,covariates = NULL,n=n)

ome_init=omega[c(2:15,1),c(2:15,1)] #ome is for testing
ome=ome_init
diag(ome)=0
```


# Initialization

## $Z_O$ distribution

```{r}
#----- PLN on counts
# optimization of theta and h(Z_O)

PLNfit<-PLN(counts~1)
MO<-PLNfit$var_par$M # MiO = ith row of MO
SO<-PLNfit$var_par$S # SiO = diag(ith row of SO)
sigma_obs=PLNfit$model_par$Sigma
```

```{r, echo=FALSE}
data.frame(melt(sigmaO)[1:2], vrai=melt(sigmaO)[3], estimation=melt(sigma_obs)[3])%>%
  rename(vrai=value, estimation=value.1 ) %>% 
  mutate(diag=(Var1==Var2)) %>% 
  ggplot(aes(vrai, estimation))+geom_point()+mytheme+labs(x="True Sigma_O",y="hat(Sigma_O)")

```


Study of the prefered quantity of noise in this example:

```{r, cache=TRUE}
B=20 ; coeff=seq(0.1,4,0.5)
varyCoeff=lapply(coeff,function(c){
  res=cbind( data.frame( t(sapply(1:B, function(x){
    init.mclust(sigma_obs,title="Sigma",
                trueClique = trueClique,n.noise=round(p*c), plot=FALSE)$FPN
  }))),c)
})
varyCoeff=do.call(rbind,varyCoeff)
colnames(varyCoeff)=c("FN","FP","coeff")

varyCoeff %>% mutate(nul = (FN==1 & FP==0)) %>% filter(!nul) %>% dplyr::select(-nul) %>%
  group_by(coeff) %>% summarise(sumFP=sum(FP), sumFN=sum(FN), sum=sum(FP+FN))

```



```{r}
initviasigma=init.mclust((cov2cor(sigma_obs)),title="Sigma",
                         trueClique = trueClique,n.noise=1)$init
initial.param<-initEM(sigma_obs,n=n,cliquelist = list(initviasigma),pca=TRUE) 
omega_init=initial.param$K0
sigma_init=initial.param$Sigma0

```


## Tree distribution

```{r}
O=1:p
Wg_init <- matrix(1, p+r, p+r); diag(Wg_init) = 0; Wg_init =Wg_init / sum(Wg_init)
W_init <- matrix(1, p+r, p+r); diag(W_init) = 0;# W_init =W_init / sum(W_init)
W_init[O,O] <- EMtree_corZ(cov2cor(sigma_obs),n = n,maxIter = 20)$edges_weight

```




# Results

## Until convergence

```{r, cache=FALSE, fig.height=12, fig.width=8}
resVEM_conv<-VEMtree(counts,MO,SO,sigma_obs,omega_init,W_init,Wg_init, eps=1e-3, alpha=1,
                maxIter=50)

```

### Edges probability matrix

```{r}
plotVEM(resVEM_conv$Pg,ome,r=1,seuil=0.5)

```


### Precision-Recall curves

```{r}
values=courbes_seuil(probs = resVEM_conv$Pg,omega = ome,h = 15,seq_seuil = seq(0,1,0.05))
plotVerdict(values, seuil)

```

### Omega estimation

```{r, echo=FALSE}
omegas = data.frame(vrai = F_Sym2Vec(ome_init) , init = F_Sym2Vec(omega_init),
                    estimation = F_Sym2Vec(resVEM_conv$omega))
omegas %>% gather(key, value, -vrai) %>% 
  ggplot(aes(as.factor(vrai), value,  fill=key, clor=key))+geom_boxplot()+
  mytheme+coord_cartesian(ylim = c(-1,2))+
  labs(x="True terms",y="Estimation",title="Omega: off-diagonal terms")


Diagomegas = data.frame(vrai = diag(ome_init) , init = diag(omega_init),
                    estimation = diag(resVEM_conv$omega))
Diagomegas %>% gather(key, value, -vrai) %>% 
  ggplot(aes(vrai, value,  color=key))+geom_point()+ theme_light()+
  scale_color_brewer("",palette = "Dark2")+
  geom_abline()+labs(x="True diagonal",y="Estimation",title="Omega: diagonal terms")
```

## After only one iteration 

```{r,fig.height=12, fig.width=8}
resVEM_1<-VEMtree(counts,MO,SO,sigma_obs,omega_init,W_init,Wg_init, eps=5e-3, alpha=1,
                maxIter=1,plot=FALSE)
resVEM_1$lowbound
```


### Edges probability matrix

```{r}
plotVEM(resVEM_1$Pg,ome,r=1,seuil=0.5)
```


### Precision-Recall curves

```{r }
values<- courbes_seuil(probs = resVEM_1$Pg,omega = ome,h = 15,seq_seuil = seq(0,1,0.05))
plotVerdict(values,seuil)
```


### Omega estimation

```{r, echo=FALSE}
omegas = data.frame(vrai = F_Sym2Vec(ome_init) , init = F_Sym2Vec(omega_init),
                    estimation = F_Sym2Vec(resVEM_1$omega))
omegas %>% gather(key, value, -vrai) %>% 
  ggplot(aes(as.factor(vrai), value,  fill=key, clor=key))+geom_boxplot()+
  mytheme+coord_cartesian(ylim = c(-1,2))+ 
  labs(x="True terms",y="Estimation",title="Omega: off-diagonal terms")


Diagomegas = data.frame(vrai = diag(ome_init) , init = diag(omega_init),
                    estimation = diag(resVEM_1$omega))
Diagomegas %>% gather(key, value, -vrai) %>% 
  ggplot(aes(vrai, value,  color=key))+geom_point()+ theme_light()+
  scale_color_brewer("",palette = "Dark2")+
  geom_abline()+labs(x="True diagonal",y="Estimation",title="Omega: diagonal terms")
```

